spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsn
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  mail:
  #    host: localhost
  #    port: 1025
  #    username: amr
  #    password: amr
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          ssl:
  #            enable: true
  #            trust: "*"
  #        starttls:
  #          enable: true
  #    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          uri: "http://localhost:9090/realms/book-network-social"
application:
  file:
    upload:
      photos-output-path: ./upload
  cors:
    origins: http://localhost:4200, http://localhost:8080

server:
  port: 8088
